# Generated by Django 2.2.4 on 2019-08-19 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('age_range', models.CharField(max_length=12)),
                ('town', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=60)),
                ('post_code', models.CharField(max_length=60)),
                ('event_type', models.CharField(max_length=60)),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField()),
                ('max_participants', models.IntegerField(max_length=3)),
                ('image', models.ImageField(blank=True, upload_to='event_images')),
                ('event_host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
