# Generated by Django 2.2.4 on 2019-08-21 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20190820_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='age_range',
            field=models.CharField(choices=[(None, 'Please Choose'), ('Babies and Toddlers', 'Babies and Toddlers'), ('Children', 'Children'), ('Teenagers', 'Teenagers'), ('Adults', 'Adults'), ('OAPs', 'OAPs')], default='Please Choose', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[(None, 'Please Choose'), ('Arts and Crafts', 'Arts and Crafts'), ('Educational', 'Educational'), ('Nature', 'Nature'), ('Entertainment', 'Entertainment'), ('Health and Wellbeing', 'Health and Wellbeing'), ('Physical and Exercise', 'Physical and Exercise')], default='Please Choose', max_length=40),
        ),
        migrations.AlterField(
            model_name='event',
            name='town',
            field=models.CharField(choices=[(None, 'Please Choose'), ('Airdrie', 'Airdrie'), ('Bellshill', 'Bellshill'), ('Biggar', 'Biggar'), ('Carluke', 'Carluke'), ('Coatbridge', 'Coatbridge'), ('East Kilbride', 'East Kilbride'), ('Hamilton', 'Hamilton'), ('Lanark', 'Lanark'), ('Larkhall', 'Larkhall'), ('Lesmahagow', 'Lesmahagow'), ('Motherwell', 'Motherwell'), ('Rutherglen', 'Rutherglen'), ('Strathaven', 'Strathaven'), ('Wishaw', 'Wishaw')], default='Please Choose', max_length=20),
        ),
    ]
