# Generated by Django 2.2.4 on 2019-08-21 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20190821_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_time',
            field=models.CharField(max_length=6),
        ),
    ]
