language: python
python:
- '3.6'
install: pip install -r requirements.txt
script:
- SECRET_KEY="secret" ./manage.py test
env:
  global:
    secure: "hRDmXaMtbvtGfIb5dJHVIMx6P9nrgmCsQrJtatgVWd4r4pALjISRXdDYyoBf+QVF3qqXlbCQsp2IUQbAbd41WpCy/XoN3TVjQQoaevbUeDRajCIaaBjIDJt7xwGSzXdQcAarqFu16JhmNyCAnPOQ9ruu7m0Jpd0umPK9UGg4YuJrx8jBCnMp9AYnXd84oPogxgKyczxt4QjSMsLs5KuvceYxiK1U8lvnSt35LW08OcxwzQqrp64sbo5O/DGvqsbPRufZfcPk/ak83qMTPlSAsHx79+rLMPRN5Kl5NhSgCcYCk4cLI3ltWuZgiBpJhaxckWfkE77Hh2LingP0ZeOa5qSxcPe/lZUnMTKOjmDkK3bFjIock24Iw84eVIjtqhPPKq9umXLCrEO9MgAJK4fOtDfvSDzDgIbrOCOB8UKWX2YsL3tf3Bx22RLMQQxzuVFtYctbj/rHKmU4i/L9453T0pgZ6q0Lx0V1c+LFrRPqJkilNZnJd/F6oiKmjB6hTiew4nVcN3spzHJ95hChnIwhzy3qtHxtWJtHOfKmO8S5laZxx30b+h9cmps6SqpW/QlRHZiqf4SJi57sZZMraOZHFx1w1zQEbXemRgSS7kUg5z9XXrPsJIQhUtmO3e8+hwNZO72D1P1yw3wLmZ4vqmiem/8pCQVIZJCLb9egPr6F8LM="
