# Generated by Django 2.2.4 on 2019-09-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='gold',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='silver',
            field=models.BooleanField(null=True),
        ),
    ]
