# Generated by Django 2.2.4 on 2019-09-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_auto_20190907_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='posts_remaining',
            field=models.IntegerField(default=0),
        ),
    ]
