# Generated by Django 2.2.4 on 2019-09-10 13:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0004_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='level',
            field=models.CharField(default='bronze', max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='membership',
            name='bronze',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='order',
            name='postcode',
            field=models.CharField(max_length=20),
        ),
    ]
